import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

export default [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: [
      '.next/**',
      '.next-dev/**',
      'node_modules/**',
      'db/migrations/**',
      '.pgdata/**',
      // Generated by Next on every build.
      'next-env.d.ts',
    ],
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      // Config files legitimately export object/array literals.
      'import/no-anonymous-default-export': 'off',
    },
  },
  {
    // The dual-driver database client selects its driver at runtime, which needs
    // require() so the unused driver is never loaded.
    files: ['db/client.ts'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
];
